POST http://localhost:8000/user/register
Content-Type: application/json

{
    "username":"IvoSerra",
    "password":"azul",
    "type":"admin"
    
}

###

POST http://localhost:8000/user/login
Content-Type: application/json



###
GET http://localhost:8000/project



###


POST http://localhost:8000/project
Content-Type:application/json

{   
    "name":"",
    "title":"Project243",
    "year":"2024",
    "description":"this is ju",
    "tools":["HTML#5", "cs.s"],
    "responsive":"",
    "repository":"https://github.com/express-validator/express-validator/issues/312",
    "deploy":"",
    "author":"LION-O",
    "video":"",
    "img":"",
    "type": "BOSS" 
}

###

POST http://localhost:8000/project
Content-Type:application/json

{   
    "name":"",
    "title":"23ivoserra",
    "year":"2021",
    "description":"this is just a testing 4",
    "tools":["HTML+", "CSS!!"],
    "responsive":"yes",
    "repository":"",
    "deploy":"",
    "author":"Ivo",
    "video":"",
    "img":"",
    "type": "EXPER" 
}

###

PATCH http://localhost:8000/project/628f799b21068dc19c07c052
Content-Type:application/json

{   
    "tools": ["html", "css","java8"]
    
}
   